---
- name: Check and Create AWX Inventory via API
  hosts: localhost
  gather_facts: false
  vars:
    awx_api_token: "WfhKgSHQKUXU6PlbvU5mPxU8tywiCS"

  tasks:
    - name: Read inventory file
      shell: cat /var/lib/awx/projects/inventory/rbarozzi-dev
      register: inventory_content
      ignore_errors: yes

    - name: Parse inventory content
      set_fact:
        parsed_inventory: "{{ inventory_content.stdout_lines }}"
      ignore_errors: yes

    - name: Get organization ID
      uri:
        url: "https://awx.rbarozzi.com/api/v2/organizations/"
        headers:
          Authorization: "Bearer {{ awx_api_token }}"
      register: organization_result
      delegate_to: localhost
      ignore_errors: yes

    - name: Get existing inventories
      uri:
        url: "https://awx.rbarozzi.com/api/v2/inventories/"
        headers:
          Authorization: "Bearer {{ awx_api_token }}"
      register: existing_inventories
      delegate_to: localhost
      ignore_errors: yes

    - name: Check and Create inventories
      uri:
        url: "https://awx.rbarozzi.com/api/v2/inventories/"
        method: POST
        headers:
          Authorization: "Bearer {{ awx_api_token }}"
        body_format: json
        body:
          name: "{{ item | regex_replace('\\[(.*)\\]', '\\1') }}"
          organization: "{{ organization_result.json.results[0].id }}"
          description: "Descrição do Novo Inventory"
      loop: "{{ parsed_inventory }}"
      when: item | regex_search('\\[.*\\]') and
            item | regex_replace('\\[(.*)\\]', '\\1') not in existing_inventories.json.results | map(attribute='name') | list
      ignore_errors: yes