- name: Execute the inventory formatting script
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Run the formatting script
      script: /home/format_inventory.sh
      become: yes
      become_user: root

    - name: Convert formatted inventory to JSON
      command: python3 /home/convert_json.py
      become: yes
      become_user: root

- name: Create Hosts and Add to AWX Inventory
  hosts: localhost
  gather_facts: false
  vars:
    awx_api_token: "WfhKgSHQKUXU6PlbvU5mPxU8tywiCS"
    awx_inventory_name: "RBAROZZI-DEV"
    host_name: "lab"
    inventory_file_path: "/var/lib/awx/projects/inventory/rbarozzi-dev-final.json"

  tasks:
    - name: Load formatted inventory content
      slurp:
        path: "{{ inventory_file_path }}"
      register: inventory_file_content

    - name: Get inventory ID by name
      uri:
        url: "https://awx.rbarozzi.com/api/v2/inventories/"
        headers:
          Authorization: "Bearer {{ awx_api_token }}"
      register: inventory_list_result
      delegate_to: localhost

    - name: Get inventory ID
      set_fact:
        inventory_id: "{{ (inventory_list_result.json.results | selectattr('name', '==', awx_inventory_name) | first).id }}"
      run_once: true

    - name: Check if host exists
      uri:
        url: "https://awx.rbarozzi.com/api/v2/hosts/"
        method: GET
        headers:
          Authorization: "Bearer {{ awx_api_token }}"
        body_format: json
      register: existing_hosts
      until: existing_hosts.status == 200
      retries: 3
      delay: 5

    - name: Verify if host already exists
      set_fact:
        host_already_exists: "{{ host_name in existing_hosts.json.results | map(attribute='name') | list }}"

    - name: Display message if host exists
      debug:
        msg: "Host {{ host_name }} already exists."
      when: host_already_exists

    - name: Create host in AWX
      uri:
        url: "https://awx.rbarozzi.com/api/v2/hosts/"
        method: POST
        headers:
          Authorization: "Bearer {{ awx_api_token }}"
          Content-Type: "application/json"
        body_format: json
        body: |
          {
            "name": "{{ host_name }}",
            "enabled": true,
            "variables": {{ inventory_file_content.content | b64decode | to_nice_json }},
            "inventory": "{{ inventory_id }}"
          }
      register: created_host
      delegate_to: localhost
      ignore_errors: yes

    - name: Add host to inventory
      uri:
        url: "https://awx.rbarozzi.com/api/v2/inventories/{{ inventory_id }}/hosts/"
        method: POST
        headers:
          Authorization: "Bearer {{ awx_api_token }}"
          Content-Type: "application/json"
        body_format: json
        body: |
          {
            "name": "{{ created_host.json.name }}"
          }
      delegate_to: localhost
      ignore_errors: yes
